### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(VehicleApplicationContent)
add_subdirectory(VehicleApplication)
add_subdirectory(App)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    VehicleApplicationContentplugin
    VehicleApplicationplugin)